name: Build Marlin for Malyan M300

on:
  push:
    branches: [ malyan-m300* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: pip install platformio
    - name: Build Marlin
      run: |
        platformio run -e malyan_M300
        mkdir firmware && touch firmware/fcupdate.flg
        mv .pio/build/malyan_M300/firmware.bin firmware/firmware.bin
    - uses: actions/upload-artifact@v1
      with:
        name: firmware
        path: firmware

